apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  namespace: argocd
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEojCCA4qgAwIBAgIUUEhijhEZ5FAPEDisyWrY6HeuIt4wDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
    MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
    MB4XDTI1MDcyMTA4NTYwMFoXDTQwMDcxNzA4NTYwMFowYjEZMBcGA1UEChMQQ2xv
    dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
    BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs8NyycAU1ikaDG+JoE3qkzJR07kZ3OEbCwXT
    FDszU3VA56filrWDR/gjTx14A3JfZic42qMtLjxRh6ODQrn72ugxTnWeTy7zaysl
    d/egKHa0a4c7iFNBsBHHAO3JJ9CIaaBQ7hDjje3ybJrnesz2zdClMnel56JrEA3q
    +eUz+T9qzYlEhLUzTcIuk67cXBJ1NhAlHzWapv0I13BbI2wvgtK+KJbi6HjBZmy3
    GUAoa/6NwBPtPa04Rz7JsVtlFteD2xlUTIIFX86gVZaa6BmVtvl0KdvTRt8MYi69
    DJOnGXGTjaqAq2OMYv5rOfTS0eXd2Cp5cAToUuiFzsXnRnXrhwIDAQABo4IBJDCC
    ASAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQX0olydoNhaFdwD3oUEC1MnW6BoDAf
    BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
    MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
    YTAlBgNVHREEHjAcgg0qLnJvZ2VyLndvcmtzggtyb2dlci53b3JrczA4BgNVHR8E
    MTAvMC2gK6AphidodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9jYS5j
    cmwwDQYJKoZIhvcNAQELBQADggEBAIFB364781NKhYV/aGJFcKx7QwYHlFGkK9dF
    VThbNcEAQbQcHB/AB/i83RmuGQl16NmJMccio55v15/zdtIUgudeUFQaGawivAhm
    9ZTDHQVwJwMeoZ+LgikrNi2LLkvXAmA7PuSXxX+7JF4iWrc5c05nlVjFdvHUNggP
    zgxAC0bxWToPtqKGY+ypOYxSqKPvmMUl33p7d2ec6ykBu1Cs33gcW3B01WLHZNlG
    YZf0/7bVh+EItiSlsr1hv2V8AC8WCE5mDNGj5ZYwODthFY47WXolxeDzSfJOWrLq
    wmWPTg2XpK4reCvofRnPnxWx1vugrYqnr4IFjDTc/6erLkQyT94=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzw3LJwBTWKRoM
    b4mgTeqTMlHTuRnc4RsLBdMUOzNTdUDnp+KWtYNH+CNPHXgDcl9mJzjaoy0uPFGH
    o4NCufva6DFOdZ5PLvNrKyV396AodrRrhzuIU0GwEccA7ckn0IhpoFDuEOON7fJs
    mud6zPbN0KUyd6XnomsQDer55TP5P2rNiUSEtTNNwi6TrtxcEnU2ECUfNZqm/QjX
    cFsjbC+C0r4oluLoeMFmbLcZQChr/o3AE+09rThHPsmxW2UW14PbGVRMggVfzqBV
    lproGZW2+XQp29NG3wxiLr0Mk6cZcZONqoCrY4xi/ms59NLR5d3YKnlwBOhS6IXO
    xedGdeuHAgMBAAECggEARW19pnUEtyf9swLbDSo6qGodV1/coMXiG3I+8UfiDWAy
    VqYtKdbl4sRv4qz3fqFMPhh06WBvYTWTqYbZ+cn5/zSBYpOjtmJkSiZKXNirJyWd
    jhAXSpIZQybCjNXJxJJSNTVhPGkSce0OHasALxn9UkU8oE68qUc+AV/WungvCBqz
    a1kZrjzKMny8aRzv2UkWCT7BvOT5rGfPqskxycCte/OtqD4IdxwEWl0btP+ukeNR
    AQkWQkveTTylSzo81QLt8ID5IAk9ONb1KIsa7wJBkmkfxy3lhwDpr4LiDXHEWxJ0
    VMSUzh2fzn0c7VfwePvsDF6JOkUWPMaua/ZUyecF/QKBgQDoPGa34hivcI2NkzFS
    8166RLRfeKoAt0Wu2HieSjMm5NCrNk2MCgw/wbo/Uk91GkO2iBWnvpN+/DWQp7M8
    sBjBXdgLR8gtthTeeD1V2jM/HC3+e08U7nwYq0uGS1/xPLeZVk5w5ykbogqLIuna
    c3YLHFRgsk1NSl/rgiE4DY3utQKBgQDGKH2PSWVx9FjX0jsHEWDtzC/ID6xEzugY
    WvIWmbuNW1mriro+oRZ6L3yTJ5IAqP/dWWtFm+IycollnxXmIczx8I9x285gUoGC
    JtBh33g4tgt+lD3WVOH01nuhg7naqJNeRtMkkai6p8o05CAYWFLv9IOi6klNbh6G
    esaRncZaywKBgF204Y2ZAXTo6XUSy3g5EyP9zPoo6g/X45olZqYYMoOjGD+9bZTw
    CPlA5jHeuIj7zA6+4l4JG+LFSafQwxXdyF9dymriz/cB3XHW+ojFvp/ccwKYJtS/
    VftuQs8xYskoQrzwgj40R/YKcE6sC8hFhn/9Ml7CE0b4l7OjklvXvElxAoGAK9hn
    t92woZ9ETTTKNM0mmldUtzqojm0Ns93jtRZ9BlERLUC75wGzvINnWBQoXRcHzk1r
    y/IrAaiQODkUGmCePWZSBwpwxqVa3JaEAzP0IPA+6NoaOKN9f7Q5lMpVxEkKmpCn
    RW8pW2um9T8Izvo0F74Npm2anJRiErV13GCBtDMCgYEAmRNl87VCYtt7dropOlXW
    jSwhxRh5/n96kGxH7nSCTCXM+QRyX2gd82z+NN0UbTvXli7hlu7rMLTuQVY8b8/V
    hfLl2vS2RYbFbiHuJpFfARbaFW9sOvOX8PokNEzpfQrvrRPVAmQsXniSfi69hWpF
    5Myv1hyXpKI1N9a/JN2tOFw=
    -----END PRIVATE KEY-----
